### PR TITLE
Allow disabling purge_ssh_keys usage on Puppetmaster older than 3.6.0

### PR DESCRIPTION
**Pull request by Phil-Friderici**
This fixes the issue described in https://github.com/ghoneycutt/puppet-module-common/issues/47

### CODE REVIEW

**Comment by ghoneycutt** [comment]
This functionality exists

https://github.com/ghoneycutt/puppet-module-common/blob/master/manifests/mkuser.pp#L113-117

**Comment by Phil-Friderici** [comment]
This only checks if the clientversion is greater than v3.6 :(

If you have the bad situation that your client is newer than your master, it will fail while compilation on the master because of unknown features.

**Comment by ghoneycutt** [comment]
It is well known that the agent cannot be newer than the master

**Comment by Phil-Friderici** [comment]
and sometimes people ignore well known details ;)

**Comment by ghoneycutt** [comment]
I think the use case is far too specific in this implementation.

We could have an optional piece of code that could compare the puppetversion of the client with that of the master and fail the catalog if the agent is newer. I think that would be more universally used than this commit which is the same in nature by very specific to one feature of an upgrade affecting v3.6.0.

What do you think?

**Comment by Phil-Friderici** [comment]
This sounds interessting and could be usefull for other use cases as well.
Any example for inspiration ?

**Comment by ghoneycutt** [comment]
No.. you would likely need to use `generate()` to get the version from the master and then compare it to the agent's fact

**Comment by Phil-Friderici** [comment]
using generate() is a good idea :) I'll play with this later on

**Pull request closed without merging**
