### PR TITLE
Manage group attribute for Mkuser home directory

### PR DESCRIPTION
**Pull request by jeffmccune**

### CODE REVIEW

**Comment by jeffmccune** [comment]
@ghoneycutt Seems to be a lot of travis failures related to MRI 1.8.7 and 1.9.3 with puppetlabs_spec_helper and puppet-lint.  I'll dig into this today, but the failures seem unrelated to the actual code changes.

**Comment by ghoneycutt** [comment]
unstage the gem stuff and I'll fix that in another pr

**Comment by jeffmccune** [comment]
> unstage the gem stuff and I'll fix that in another pr

Unstaged

**Comment by ghoneycutt** [comment]
Cancelled Travis on this. Once PR #59 gets merged, could you please rebase and then tests should pass.

**Comment by ghoneycutt** [comment]
CC: @ramamaddodi

**Comment by ghoneycutt** [comment]
Released in v1.8.0

**Pull request merged**
