### PR TITLE
Ensure path to $HOME exists

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@Phil-Friderici @sharlander 

You two are using this module to max with all of its options. Would you mind running puppet in noop with this code in your respective work environments to make sure I'm not breaking anything.

Thanks!!

**Comment by sharlander** [comment]
@ghoneycutt i'm on vacation till 11th, so i can't run it in my work env,
anyway it looks fine the only thing i found is "managehome" it also needs a string to bool conversion like "manage_dotssh" got

because usually in hiera all my values are quoted like:
<pre>
common::users:                                                                                                                                                                                
  sth:                                                                                                                                                                                        
    ensure: 'present'                                                                                                                                                                         
    uid: '30000'                                                                                                                                                                              
    gid: '30000'                                                                                                                                                                              
    password: '123456'                                                                                                                                                                        
    groups: 'wheel'                                                                                                                                                                           
    managehome: 'true'                                                                                                                                                                        
    manage_dotssh: 'true' 
</pre>

**Comment by ghoneycutt** [comment]
@sharlander Good catch! I added the str2bool bits.

**Comment by ghoneycutt** [comment]
@Phil-Friderici How does this look to you?

**Comment by Phil-Friderici** [comment]
Code looks good to me, just the spec test for stringified bool handling are missing ;)
Let me add them

**Comment by Phil-Friderici** [comment]
@ghoneycutt added the spec tests in https://github.com/ghoneycutt/puppet-module-common/pull/52

**Comment by ghoneycutt** [comment]
using PR #52 

Thanks @sharlander @Phil-Friderici

**Comment by ghoneycutt** [comment]
Released in v1.5.0

**Pull request merged**
